### ISSUE TITLE
Es6 import is not working

### ISSUE THREAD

**Issue by caracal7** [timkendrick/monaco-editor#2]
`import monaco from '@timkendrick/monaco-editor';`

TypeError: undefined is not an object (evaluating '__WEBPACK_IMPORTED_MODULE_6__timkendrick_monaco_editor___default.a.editor')

but CommonJS work fine

**Comment by timkendrick** [comment]
Hi there – sorry for such a delayed response, for some reason I've only just seen this message.

Looks like you're using the `import default` syntax, whereas if you look closely at the readme example for ES6 module usage, it should be the following (note the `*`):

```js
import * as monaco from '@timkendrick/monaco-editor';
```

Feel free to reopen if you're still having problems.
