### ISSUE TITLE
Add `monaco.d.ts` file into package for typescript

### ISSUE THREAD

**Issue by panoti** [timkendrick/monaco-editor#3]
Can you add `monaco.d.ts` file into your package for intellisense?

**Comment by brownbl1** [comment]
Agreed, this would be very helpful for exploring the API.

**Comment by timkendrick** [comment]
Hi there – sorry for the delayed response, I didn't see this issue until today for some reason. I've just published v0.0.8 which contains typings for both the standalone and external versions.

The typings seem to work well in VSCode using the `import * as monaco from '@timkendrick/monaco-editor';` syntax (in both JS and TS), but feel free to reopen the issue if you come across problems with the typings.

**Comment by brownbl1** [comment]
Yep, looks great!
