### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MSeifert04** [timkendrick/monaco-editor#5]
This repository doesn't have a license which means that noone should use/modify it (source: https://choosealicense.com/no-permission/).

More specifically: Am I allowed to use a modified version of the code and if so under which license (or is it ISC like the npm module)?

**Comment by timkendrick** [comment]
I've just added a `LICENSE` file and updated the license in `package.json` to `MIT`, to match the license on [monaco-editor](https://github.com/Microsoft/monaco-editor). I previously just used the npm default of `ISC` in `package.json`, which as far as I understand is basically the same. So yep, it's now officially MIT-licensed, thanks for raising this.

As for whether it's a wise idea to use it in production in the first place – it's an experimental package, and while it's stable and will be updated sporadically, it's not officially supported, so bear that in mind if you're using it on large projects.

**Comment by MSeifert04** [comment]
Thank you!
